=== ജനനവും ബാല്യവും

നമ്മുടെ കഥാനായകൻ്റെ കഥ പറയും മുമ്പേ അദ്ദേഹം ജനിച്ച സ്ഥലത്തെക്കുറിച്ചും കാലഘട്ടത്തെക്കുറിച്ചും അല്പം മനസിലാക്കുന്നത് പ്രയോജനകരമായിരിക്കും.

1800കളുടെ ആദ്യവർഷങ്ങളിൽ യൂറോപ്പ് യുദ്ധങ്ങളാലും വിപ്ലവങ്ങളാലും കലുഷിതമായിരുന്നു. നെപ്പോളിയൻ്റെ നേതൃത്വത്തിലുള്ള ഫ്രഞ്ച് സൈന്യവുമായി മറ്റു യൂറോപ്യൻ രാജ്യങ്ങൾ നിരന്തരയുദ്ധത്തിലേർപ്പെട്ടുകൊണ്ടിരുന്ന ഒരു കാലഘട്ടമായിരുന്നു അത്. അതേ സമയം യാഥാസ്ഥിക ചിന്തകൾക്കും ചിന്തകർക്കും പ്രചാരവും പ്രശസ്തിയും ദിനംപ്രതിയെന്നോണം വർദ്ധിച്ചു വന്നു. നവീകരണത്താലുളവായ ഉണർവിൻ്റെ അലയൊലികൾ ക്രമേണ അടങ്ങിരികയും ചെയ്തു. 

ഇക്കാലയളവിൽ ജർമ്മനിയിലെ സ്റ്റട്ട്ഗാർട്ടിൽ (Stuttgart) ജീവിച്ചിരുന്ന ദൈവഭക്തരായ ലുഡ്വിഗ് ഗുണ്ടർട്ട്, ക്രിസ്റ്റ്യൻ ആൻസ്ലിൻ എന്ന ദമ്പതികളുടെ മൂന്നാമത്തെ കുട്ടിയായി 1814 ഫെബ്രുവരി 14ന് ഹെർമൻ ഗുണ്ടർട്ട് പിറന്നു. ദൈവികകാര്യങ്ങളിൽ അതീവതത്പരനായിരുന്ന ലുഡ്‍വിഗ് പ്രാദേശിക ബൈബിൾ സൊസൈറ്റിയുടെ സെക്രട്ടറിയായി പ്രവർത്തിച്ചിരുന്നു. അതോടൊപ്പം തൻ്റെ നാട്ടുകാരെ മിഷൻപ്രവർത്തനങ്ങൾക്ക് പ്രോത്സാഹിപ്പിക്കുക എന്ന ലക്ഷ്യത്തോടെ ഒരു മിഷൻ മാഗസിനും അദ്ദേഹം തുടക്കം കുറിച്ചു. ക്രിസ്റ്റ്യാനാകട്ടെ, തൻ്റെ പൈതങ്ങളെ ചെറുപ്പം മുതൽ ദൈവവചനത്തിലും പ്രാർത്ഥനയിലും ഉത്സാഹിപ്പിച്ചുപോരുകയും ചെയ്തു. യുദ്ധം സൃഷ്ടിച്ച കഠിനസാഹചര്യങ്ങളിലും ലുഡ്‍വിഗും കുടുംബവും ദൈവത്തിൽ ആശ്രയം കണ്ടെത്തി.

ഇങ്ങനെയുള്ള ഒരു ഭവനത്തിൽ ജനിച്ച ഹെർമൻ ഒരു മിഷണറിയായതിൽ അത്ഭുതം ഏതും വേണ്ടെന്ന് ഒരുപക്ഷേ നമ്മൾ ചിന്തിച്ചേക്കാം. എന്നാൽ യാഥാർഥ്യം വേറൊന്നായിരുന്നു. തൻ്റെ ചെറിയ പ്രായം മുതൽതന്നെ ദൈവികകാര്യങ്ങളെക്കാൾ ലൗകികകാര്യങ്ങളാണ് കൊച്ചുഹെർമനെ ആകർഷിച്ചിരുന്നത്. വെറും രണ്ടുവയസുമാത്രം പ്രായമുള്ളപ്പോൾ അവൻ തൻ്റെ മാതാവിനോട് ഇപ്രകാരം പറഞ്ഞുവെന്ന് ക്രിസ്റ്റ്യാൻ തൻ്റെ ഡയറിയിൽ കുറിച്ചിട്ടു: 
[quote, ഹെർമൻ ഗുണ്ടർട്ട്, ക്രിസ്റ്റ്യാനയുടെ ഡയറിയിൽനിന്നും]
“ഞാൻ വലുതാകുമ്പോൾ ഏതായാലും ഒരു പാതിരിയാകില്ല. ഞാനൊരു പട്ടാളക്കാരനാകും, തോക്കും എടുക്കും ചെണ്ടയും മുട്ടും”.

ഇതുകേട്ട മാതാവിനുള്ള ദുഃഖം എത്രയായിരുന്നുവെന്ന് പറയേണ്ടതുണ്ടോ?

ഹെർമൻ മുതിർന്നു വരുംതോറും അവന് ദൈവികകാര്യങ്ങളിലെ താത്പര്യം കുറഞ്ഞുകുറഞ്ഞു വന്നു. ആ ഭക്തരായ മാതാപിതാക്കളാകട്ടെ, തങ്ങളുടെ താന്തോന്നിയായ മകനെ പ്രാർത്ഥനയ്ക്കായും ദൈവവചനവായനയ്ക്കായും നിർബന്ധിക്കുകയും ദൈവഭക്തിയിൽ വളർത്തിക്കൊണ്ടുവരുവാൻ തങ്ങളാൽ ആവുംവിധം യത്നിക്കുകയും ചെയ്തു. അവരുടെ പ്രയത്നങ്ങൾക്കൊന്നും ആ സമയം ഹെർമനിൽ വലിയ മാറ്റങ്ങളുണ്ടാക്കാനായില്ലെങ്കിലും താൻ തത്വചിന്തകളിൽനിന്നും ലോകസ്നേഹത്തിൽനിന്നും ദൈവത്തിലേയ്ക്കുള്ള തൻ്റെ മടങ്ങിവരവ് മാതാപിതാക്കളുടെ നിരന്തരമായ പ്രാർത്ഥനയുടെയും ഉപദേശത്തിൻ്റെയും ഫലമായിരുന്നുവെന്ന് പിന്നീടൊരിക്കൽ ഗുണ്ടർട്ട് അനുസ്മരിക്കുവാനിടയായി.

ബാല്യം മുതൽ പഠനത്തിൽ അതീവസമർഥനായിരുന്നു ഹെർമൻ. 1815-ലെ നെപ്പോളിയൻ്റെ പരാജയത്തോടെ യുദ്ധം അവസാനിച്ചതിനാൽ തനിക്ക് പഠിക്കുവാനനുകൂലമായ സാഹചര്യവും അപ്പോഴേക്കും ഉരുത്തിരിഞ്ഞുവന്നു. 5-ാം വയസിൽ ഹെർമൻ ലാറ്റിൻ ഭാഷ സ്വയം പഠിച്ചു തുടങ്ങി. 13 വയസായപ്പോഴേക്കും ആ ബാലൻ മാൾബ്രൺ സെമിനാരിയിലേക്ക് പഠിപ്പു മാറ്റി ലാറ്റിനൊപ്പം ഗ്രീക്ക്, എബ്രായ ഭാഷകളും ഇംഗ്ലീഷും ഫ്രഞ്ചും കൂടി പഠിക്കുവാനാരംഭിച്ചു. സയൻസും, ജ്യോഗ്രഫിയും, കണക്കും പഠിക്കുന്നതിനു കൂടെയാണിതെന്നോർക്കണം. ഇത്രയുമൊന്നും പോരാഞ്ഞ് സംഗീതവും, പിയാനോ വായനയും കൂടി ഹെർമൻ സ്വായത്തമാക്കി. ഇങ്ങനെ എല്ലാം നന്നായിപ്പോകുമ്പോഴാണ് 1827ൽ ഹെർമൻ്റെ ഒരു സഹോദരനും സഹോദരിയും മരണപ്പെട്ടത്. തൻ്റെ കുഞ്ഞുപെങ്ങളുടെ മരണം ഹെർമനെ വല്ലാതെയുലച്ചു. മരണത്തെക്കുറിച്ചുള്ള ചിന്ത ആ മനസിനെ വ്യാകുലപ്പെടുത്തുവാൻ തുടങ്ങി. അങ്ങനെ ഒരു നല്ലകുട്ടിയായിത്തീരുവാൻ ഹെർമൻ തീരുമാനമെടുത്തു. എങ്കിലും ഇത് അധികകാലം നീണ്ടുനിന്നില്ല. പ്രാർത്ഥനകളും, വചനവായനയും വിരസമായി തോന്നിയ ഹെർമൻ, വീണ്ടും കവിതകളിലും നാടകങ്ങളിലും ആനന്ദം കണ്ടെത്തുകയും ചെയ്തു. 

വിഖ്യാത ജർമൻ കവിയായ ശില്ലറിൻ്റെ (Friedrich Schiller) കവിതകളിൽ അത്യന്താകൃഷ്ടനായ ഹെർമൻ താൻ‍ മുതിർന്നുവരുമ്പോൾ ഒരു കവിയോ, നാടകകൃത്തോ ആയിത്തീരേണം എന്നും ആശിച്ചു. എന്നാൽ തൻ്റെ പിതാവാകട്ടെ, “നാടകങ്ങൾക്ക് പാട്ടെഴുതുന്നവനെപ്പോലെ നികൃഷ്ടനായി ആരുമില്ല, എൻ്റെ കാഴ്ചയിൽ ഒരു വിറകുവെട്ടുകാരന് അവനെക്കാൾ വിലയുണ്ട്. അതുകൊണ്ട് നീ ഭംഗി, സത്യം, നന്മ എന്നിവ കാംക്ഷിച്ചാൽ എനിക്കു സന്തോഷം. നീയൊരു ലോകസ്നേഹിയും സ്വപ്നാടനക്കാരനും ആകരുതേ” എന്ന് ഒരു കത്തിലൂടെ അവനെ ഉത്ബോധിപ്പിച്ചു. ക്രിസ്റ്റീനയാകട്ടെ തൻ്റെ മകൻ കേവലം ലൗകികതയുടെ പിമ്പേ പോകുന്നതിൽ മനം തകർന്ന് തൻ്റെ രോഗപീഢപോലും വകവയ്ക്കാതെ ദീർഘദൂരം യാത്രചെയ്ത് തൻ്റെ മകനെ സന്ദർശിച്ചു അവനെ ക്രിസ്തുവിൻ്റെ സ്നേഹത്തിലേയ്ക്ക് മടക്കിക്കൊണ്ടുവരുവാൻ ശ്രമിച്ചു. എന്നാൽ ഇതിനാലൊന്നും ഹെർമനിൽ യഥാർഥമായ ഒരു മാനസാന്തരം ഉളവായില്ല. എന്നുമാത്രമല്ല, തൻ്റെ സുഹൃത്‍വലയത്തിൻ്റെ സ്വാധീനത്താൽ ദൈവികപാതയിൽനിന്നും മേൽക്കുമേൽ അവൻ അകന്നു മാറുകയും ചെയ്തു. 

1830-ൽ സുഹൃത്തിൻ്റെ കൈയബദ്ധത്താൽ ഒരു കത്തി ഹെർമൻ്റെ നെഞ്ചിനോട് എത്രയും അടുത്തൊരു സ്ഥലത്ത് തറച്ചു താൻ മരണപ്പെട്ട് പോകുവാൻ പോലും ഇടയുണ്ടായിരുന്നു. ഈ സംഭവം ആ ചെറുപ്പക്കാരനെ ആസകലം ഉലച്ചു. പിന്നീട് കുറെനാളേക്ക് ഭക്തിമാർഗത്തിലേക്ക് തിരിഞ്ഞ ഹെർമൻ കർത്താവിനെ അന്വേഷിക്കാൻ ആരംഭിച്ചു. എന്നാൽ ഇതും അധികകാലം നീണ്ടുനിന്നില്ല. ഫ്രഞ്ച് വിപ്ലവം ഉണ്ടാക്കിയ സ്വാതന്ത്ര്യാസക്തിയുടെ അലയടികൾ ഹെർമൻ്റെ ശ്രദ്ധയെ വീണ്ടും ദൈവത്തിങ്കൽനിന്നും തിരിച്ചുകളഞ്ഞു. വിപ്ലവാഹ്വാനം നടത്തുന്ന ലേഖനങ്ങൾ എരിവേറിയഭാഷയിൽ തദ്ദേശീയ ദിനപ്രത്രങ്ങളിൽ ഹെർമൻ പ്രസിദ്ധപ്പെടുത്തിപ്പോന്നു. അക്കാലത്ത് മാൾബ്രനിൽ അധ്യാപകനായി വന്ന സ്റ്റ്രോസ് (David Strauss) എന്ന പണ്ഡിതൻ്റെ ലിബറൽചിന്താഗതികളിൽ ആകൃഷ്ടനായ അദ്ദേഹം ദൈവത്തോടു മാത്രമല്ല, സ്വന്തം മാതാപിതാക്കളോടുപോലും അകലുവാനാരംഭിച്ചു. തങ്ങളുടെ മകൻ്റെ ചര്യകളിൽ മനംനൊന്തുപോയ ആ മാതാപിതാക്കളാകട്ടെ തങ്ങളുടെ ദുഃഖം ദൈവസന്നിധിയിൽ നിരന്തരം പ്രാർത്ഥനകളായി അർപ്പിച്ചുപോരുകയും ചെയ്തു.

ഇവ്വിധം ഉഴന്നുപോയ ആ ബാല്യക്കാരനിൽ മാനുഷികമായ യാതൊരുവിധ പ്രയത്നങ്ങൾക്കും രൂപാന്തരം ഉളവാക്കാനായില്ലെങ്കിലും ദൈവം തന്നെ അവനെ ദൈവവിശ്വാസത്തിലേയ്ക്കും മാനസാന്തരത്തിലേയ്ക്കും മടക്കിയെത്തിച്ചു.

ദൈവഭക്തരായ ലുഡ്‍വിഗും ക്രിസ്റ്റ്യാനും ദൈവസന്നിധിയിൽ കഴിച്ച പ്രാർത്ഥനകൾക്ക് ദൈവം മറുപടികൊടുത്ത കഥ അടുത്ത അദ്ധ്യായത്തിൽ.