=== ഗുണ്ടർട്ടിൻ്റെ മാനസാന്തരം

1830-ാമാണ്ട് ഒക്ടോബർ മാസത്തിൽ ഹെർമൻ ഗുണ്ടർട്ട് ജർമ്മനിയിലെ പ്രസിദ്ധമായ ത്യൂബിങ്ങൻ യൂണിവേഴ്സിറ്റിയിൽ ചേർന്നു. വൈകാതെതന്നെ തൻ്റെ പ്രിയ അദ്ധ്യാപകനായിരുന്ന സ്റ്റ്രോസും ത്യൂബിങ്ങനിൽ എത്തിച്ചേർന്നു. സ്റ്റ്രോസാകട്ടെ ഇതിനോടകം വിഖ്യാത ജർമ്മൻ തത്വചിന്തകനായ ഹേഗലിൻ്റെ (Georg Wilhelm Friedrich Hegel) തത്വചിന്തകളുടെയും സിദ്ധാന്തങ്ങളുടെയും സ്വാധീനതയിലായിത്തീർന്നിരുന്നു. അദ്ദേഹം തൻ്റെ ശിഷ്യന്മാരിലേയ്ക്കും എത്രയും വാക്ചാതുര്യതയോടും യുക്തിയോടും കൂടെ ഈ നവയുഗചിന്തകൾ പകർന്നുകൊടുത്തു. സ്വതേ സ്വതന്ത്രേച്ഛുവായ ഹെർമനും ഈ വലയത്തിനുള്ളിലായി എന്ന് പ്രത്യേകം പറയേണ്ടതില്ലല്ലോ. യാഥാസ്തിക ക്രിസ്തീയമൂല്യങ്ങൾ പിന്തുടർന്ന സഹപാഠികൾ കേവലം മൂഢന്മാർ ആണെന്ന് ഇക്കൂട്ടർ ധരിച്ചുപോരുകയും ചെയ്തു. ഇതുമൂലം അനേകം യൗവനക്കാർ തങ്ങളുടെ പിതാക്കന്മാരുടെ മാർഗം വിട്ടു യുക്തിവാദികളായി (rationalists) തീരുവാനിടയായി.

ഇക്കാര്യം അറിഞ്ഞ ലുഡ്‌വിഗ് ദീർഘമായൊരു കത്ത് തൻ്റെ മകന് എഴുതി, 

[quote, ലുഡ്‌വിഗ് ഗുണ്ടർട്ട്, ഗുണ്ടർട്ടിനയച്ച കത്തിൽനിന്നും]
“മകനേ നീ സത്യമാർഗത്തിൽ നിന്നും വഴിതെറ്റി മണലിന്മേൽ വീട് പണിതവനെപ്പോലെ ആയിപ്പോയിരിക്കുന്നു” 

എന്ന് അവനെ ഓർപ്പിച്ചു. കേവലയുക്തിക്ക് അതീതമായ ദൈവികശക്തിയെ തൻ്റെ മകൻ ഗ്രഹിക്കണമെന്ന് അദ്ദേഹം ആഗ്രഹിച്ചു. അവൻ സുവിശേഷത്തെ യുക്തികൊണ്ട് വിശകലനം ചെയ്യുന്നതിനുപകരം സുവിശേഷത്തോട് യുക്തി ചേർത്തിണക്കും എന്ന് താൻ ആശിച്ചു. 
[quote]
“നീ കേവലം ഈ പിതാവിൻ്റെ സ്നേഹത്തിനു മാത്രമല്ല ദൈവാത്മാവിൻ്റെ ശബ്ദം കേൾപ്പാനുമായി നിൻ്റെ ചെവി തുറന്നുവരുവാനിടയാകട്ടെ എന്നു ഞാൻ പ്രാർത്ഥിക്കുന്നു” 

എന്നെഴുതിയാണ് അദ്ദേഹം തൻ്റെ കത്ത് അവസാനിപ്പിച്ചത്. ഒരു ദൈവപ്രവർത്തിക്കല്ലാതെ മാനുഷികവാക്കുകൾക്ക് തൻ്റെ മകനിൽ യാതൊരുമാറ്റവും വരുത്താനാവില്ലയെന്ന് ആ ദൈവമനുഷ്യനു ബോധ്യമായി.

ക്രിസ്ത്വബ്ദം 1833 ജനുവരി മാസത്തിൽ ഹെർമൻ്റെ മാതാവ് തൻ്റെ ഇഹലോകവാസം അവസാനിപ്പിച്ച് താൻ പ്രിയം വെച്ച കർത്താവിനരികിലേയ്ക്ക് പോയി. അപ്പോഴേയ്ക്കും ആ അമ്മയുടെ അരുമയായ മകൻ “ഒരു ശുദ്ധ അജ്ഞാനിയായിത്തീർന്നിരുന്നു”. എന്നാൽ അക്കാലത്തുപോലും ഗുണ്ടർട്ട് ഒരിക്കലെങ്കിലും സ്ഥൂലമായ പാപങ്ങളിലകപ്പെടുകയോ ദുർന്നടപ്പ് ആചരിക്കുകയോ ചെയ്തിരുന്നില്ല എന്നുമാത്രമല്ല തൻ്റെ പിതാവിന് തന്നെക്കൊണ്ട് ഒരു ഭാരവും ഉണ്ടാകരുത് എന്ന് കരുതി തൻ്റെ പണം അതിസൂഷ്മത്തോടെ ചെലവ് കഴിക്കുകയും ചെയ്തുപോന്നു എന്ന കാര്യവും പ്രസ്താവ്യമാണ്. കല, തത്വജ്ഞാനം, യുക്തിവാദം എന്നിത്യാദി ബൗദ്ധികകാര്യങ്ങളിലായിരുന്നു അദ്ദേഹത്തിന് താത്പര്യം. ഇവയാണ് അദ്ദേഹത്തെ ദൈവികകാര്യങ്ങളിൽനിന്നും അകറ്റിക്കളഞ്ഞത്.

സ്റ്റ്രോസിൻ്റെ സ്വാധീനവലയത്തിലകപ്പെട്ട് തങ്ങളുടെ വിശ്വാസം ത്യജിച്ചവരായ അനേകർ ആ സർവകലാശാലയിലുണ്ടായിരുന്നു. അസാധാരണ ബുദ്ധിപാടവവും, യുക്തിബോധവുമുള്ള ഹെർമൻ ക്രമേണ ഇവർക്കിടയിൽ ഒരു നേതാവായിത്തീരുകയും ചെയ്തു. എന്നാൽ ഈ ചങ്ങാതിമാരിൽ പലരും ജീവിതത്തിൻ്റെ അർത്ഥം നഷ്ടപ്പെട്ടരായി നിരാശരായിത്തീരുകയും ചിലർ ക്രമേണ ആത്മഹത്യയിൽ അഭയം തേടുകയും ചെയ്തു. ഇവരെ ധൈര്യപ്പെടുത്തുവാനോ തക്കതായ വഴികാട്ടിക്കൊടുക്കുവാനോ ഹെർമനായില്ല. താൻതന്നെ ഒരു സാക്ഷാൽ ഭ്രാന്തനായിത്തീരുമോ എന്ന് ശങ്കിച്ചുപോയി എന്ന് അദ്ദേഹം പിൽക്കാലത്ത് എഴുതി. ഇക്കാലയളവിലൊരിക്കൽ ഹെർമൻ്റെ ഒരു ആത്മസ്നേഹിതൻ ആത്മഹത്യക്കായി ഒരുങ്ങി. അവനെ അതിൽനിന്നും പിന്തിരിപ്പിപ്പാൻ ഹെർമൻ കിണഞ്ഞുപരിശ്രമിച്ചുവെങ്കിലും അവൻ വഴങ്ങിയില്ല. അതിദുഃഖിതനായിത്തീർന്ന ഹെർമൻ മറ്റൊരുവഴിയും കാണാനാകാതെ അവസാനം തൻ്റെ സുഹൃത്തിനു ഒരു മനംമാറ്റം ഉണ്ടാകണമേ എന്ന് ദൈവത്തോട് കേണപേക്ഷിച്ചു. ആ പ്രാർത്ഥനയെ സ്വർഗസ്ഥനായ പിതാവ് ദയയോടെ കേട്ടു. ആ പ്രാർത്ഥനയെക്കുറിച്ച് ഗുണ്ടർട്ട് ഇപ്രകാരം ആണെഴുതിയിരിക്കുന്നത്: 

[quote, ഗുണ്ടർട്ട്, ഡയറിക്കുറിപ്പ്]
“ഞാൻ ആ രാത്രിയിൽ സാക്ഷാൽ നിരാശപ്പെട്ടു ദരിദ്രനും ഗതിയില്ലാത്തവനുമായി ദൈവത്തെ അന്വേഷിച്ചതുകൊണ്ടു വളരേ അറ്റകുറ്റംകൊണ്ടു നിറഞ്ഞ ആ പ്രാൎത്ഥന ദൈവം കേട്ടു മഴ പെയ്തു തോൎന്നു ആകാശവും തെളിഞ്ഞു വന്നു നക്ഷത്രങ്ങൾ മേലിൽനിന്നു മിന്നുന്നതും കാണായി. എന്റെ ഹൃദയത്തിലുള്ള ക്ഷോഭവും ചുഴലിയും ശമിച്ചാൽ എനിക്കു ലഭിച്ച രക്ഷ ഞാൻ ഇന്ത്യയിൽ ചെന്നറിയിക്കും എന്നും അന്നുതന്നെ നിർണ്ണയിച്ചു.” 

തത്വചിന്തയിലുള്ള താത്പര്യം കൊണ്ടായിരിക്കാം ഇന്ത്യയെന്ന ചിന്ത ഒരുപക്ഷേ തന്നിൽ വന്നത്.

തൻ്റെ പ്രാർത്ഥനയ്ക്ക് ദൈവം മറുപടിതന്നുവെന്ന് കണ്ട ഹെർമൻ താനെടുത്ത തീരുമാനത്തിനനുസൃതമായി ക്രിസ്തീയകൂട്ടായ്മകളിൽ കൂടുതലായി പങ്കെടുക്കാനാരംഭിച്ചു. ഈ സംഭവം ഹെർമനിൽ ഒരു യഥാർഥ മാനസാന്തരത്തിനു ഹേതുവായില്ലെങ്കിൽക്കൂടി ദൈവികമാർഗത്തിലേക്കുള്ള മടങ്ങിപ്പോക്കിൻ്റെ ആദ്യപടിയായിരുന്നു അത്. അപ്പോൾപ്പോലും അത്തരം കൂട്ടായ്മകളിൽ ജ്ഞാനികൾ എന്ന് കരുതാവുന്നർ ആരെയും കാണായ്കയാൽ അവരോടൊപ്പം ഇടപഴകുന്നതിൽ അല്പമല്ലാത്ത വൈമുഖ്യവും തനിക്കുണ്ടായി. തൻ്റെ മുൻസുഹൃത്തുക്കൾ പലരും ഹെർമനെ വീണ്ടും സ്വാധീനിക്കാൻ ശ്രമിക്കയാൽ അവിശ്വാസമാകുന്ന ഈശാനമൂലൻ പലവട്ടം ആഞ്ഞടിച്ച് ആ കപ്പലിൻ്റെ നങ്കൂരം വീണ്ടും തകർന്നുപോകുമോയെന്ന് ശങ്കിക്കേണ്ടുന്ന അവസ്ഥ വീണ്ടും ഉളവായി. ഇങ്ങനെ രണ്ടുവഞ്ചിയിൽ കാൽവെപ്പാൻ ശ്രമിച്ച് അദ്ദേഹം നിരാശയിൽ അകപ്പെട്ട് വിശ്വാസം വീണ്ടും ത്യജിച്ചുകളയുന്നയിടത്തോളം വീണ്ടും എത്തി. എന്നാൽ 1837-ലെ വസന്തകാലത്ത് വൃക്ഷങ്ങളിൽ പുതുജീവൻ നാമ്പിടുന്നതോടൊപ്പം ഹെർമനിലും യഥാർഥമാനസാന്തരത്തിൻ്റെ തളിരുകൾ പൊട്ടിമുളയ്ക്കുവാൻ കർത്താവിടയാക്കി. എന്നാൽ ദൈവം അതിനായി തിരഞ്ഞെടുത്തവഴി മരണത്തിലൂടെ ജീവങ്കലേയ്ക്ക് കടക്കുന്നതായിരുന്നു. 

അതെങ്ങനെയെന്നാൽ ഹെർമൻ ഒരു സന്നിജ്വരബാധിതനായി, രോഗം മൂർച്ഛിച്ച് മരണാസന്നനായിത്തീർന്നു. ചിലമാസങ്ങളോളം ഒരു ബലഹീനശിശുവെന്നപോലെ ജീവനായി പൊരുതി ക്രിസ്തുവിനോട് ഒരു വിടുതലിനായി പ്രാർത്ഥിച്ചുകൊണ്ടിരുന്നു. ഹെർമനെക്കുറിച്ച് ഒരു ദൈവികപദ്ധതിയുണ്ടായിരുന്നതിനാൽ കർത്താവ് ആ രോഗത്തിനു ശമനം വരുത്തി. അങ്ങനെ സൗഖ്യം പ്രാപിച്ചതിനു ശേഷം ഹെർമൻ തൻ്റെ മുൻസുഹൃത്തുക്കളുമായുള്ള ബന്ധം പാടെ ഉപേക്ഷിച്ച് വിരലിലെണ്ണാൻ മാത്രമുണ്ടായിരുന്ന ക്രിസ്ത്യൻ സുഹൃത്തുക്കളുടെ കൂട്ടായ്മയിൽ പങ്കുചേരുവാൻ തുടങ്ങി. 

അങ്ങനെയിരിക്കെ ഒരു ദിവസം “ഹൃദയശുദ്ധിയുള്ളവർ ഭാഗ്യവാന്മാർ; അവർ ദൈവത്തെക്കാണും” എന്ന വചനത്തെ ആധാരമാക്കി ഒരു പ്രസംഗം നടത്തേണ്ടതിനായി ഹെർമനു ക്ഷണം വന്നു. അതിലേയ്ക്കായി വചനം ധ്യാനിച്ചുകൊണ്ടിരിക്കുമ്പോൾ അദ്ദേഹത്തിനു തൻ്റെ ഹൃദയത്തിൻ്റെ പരിതാപകരമായ മലിനാവസ്ഥ വെളിവായ്‌വരികയും അതിൽനിന്നും എങ്ങനെയും രക്ഷപെടേണം എന്ന തീഷ്ണമായ ആഗ്രഹം തന്നിൽ ഉടലെടുക്കുകയും ചെയ്തു. പാപബോധത്താൽ മനംകലങ്ങിയ ആ യൗവനക്കാരൻ മുട്ടുകുത്തി ക്രൂശിതനോട് തൻ്റെ പാപങ്ങളെ മോചിച്ചുതരേണമെന്ന് മുട്ടിപ്പായി പ്രാർത്ഥിച്ചു. ആ നാഴികയിൽത്തന്നെ ഹെർമന് ദൈവികകൃപ അനുഭവിച്ചറിയുവാനും തൻ്റെ കല്ലായ ഹൃദയത്തിനുപകരം താൻ അനുതാപമുള്ള നിർമലമായ ഒരു ഹൃദയത്തിനുടമയായിത്തീരുവാനും ഇടയായിത്തീർന്നു. 

പ്രത്യാശയ്ക്കൊരു വകപോലും കാണാൻ സാധ്യമല്ല എന്ന് കരുതിയയിടത്ത് ദൈവസ്നേഹം ഹെർമനെ തേടിയെത്തി. ഗുണ്ടർട്ട് ആ അനുഭവത്തെക്കുറിച്ച് പിന്നത്തേതിൽ “അന്നുതൊട്ടു ചിലതിന്നൊക്കേയും ഭംഗം വന്നാലും ഞാൻ അവനിൽ വസിച്ചു അവന്റെ ആളായി ജീവനാൾ കഴിപ്പാൻ ഇടയായതുനിമിത്തവും ഞാൻ കൎത്താവിനെ പുകഴ്ത്തുന്നു” എന്നെഴുതുവാൻ ഇടയായി. ദൈവഭക്തരായ ആ മാതാപിതാക്കൾ ദൈവസന്നിധിയിൽ കഴിച്ച പ്രാർത്ഥനകൾക്കും കണ്ണുനീരിനും ദൈവം മറുപടിനൽകി.

പ്രിയവായനക്കാരെ, നിങ്ങളും ഗുണ്ടർട്ടിൻ്റെ മാതാപിതാക്കളെപ്പോലെ നിങ്ങളുടെ പ്രിയപ്പെട്ടവരുടെ മാനസാന്തരത്തിനായി പ്രാർത്ഥിച്ചു മറുപടികാണാതെ മനംകലങ്ങിയിരിക്കുന്നവരാണോ? നിങ്ങൾ നിരാശരാകാതെ പ്രാർത്ഥനയിൽ ഉറ്റിരിപ്പിൻ. യേശു പറഞ്ഞു: “എന്നെ അയച്ച പിതാവ് ആകർഷിച്ചിട്ടല്ലാതെ ആർക്കും എന്റെ അടുക്കൽ വരുവാൻ കഴികയില്ല…”. അവൻ തക്കസമയത്ത് നിങ്ങളുടെ പ്രാർത്ഥനയ്ക്കുള്ള മറുപടി അയയ്ക്കുകതന്നെ ചെയ്യും.
