=== ഇന്ത്യയിലെ ആദ്യ സംവത്സരങ്ങൾ

ഗ്രോവ്സിനോടൊപ്പം മദ്രാസിൽ (ഇപ്പോഴത്തെ ചെന്നൈ) ചെലവിട്ട ആദ്യനാളുകൾ ഗുണ്ടർട്ടിന് കടുത്ത ആത്മസംഘർഷത്തിൻ്റേതായിരുന്നു. കൽക്കത്തയിൽ മിഷണറിവേല ചെയ്യുക എന്ന ലക്ഷ്യം മുൻനിർത്തി ഇന്ത്യയിലെത്തും മുമ്പേ തന്നെ അദ്ദേഹം ബംഗാളിയും, തെലുങ്കും, ഹിന്ദുസ്ഥാനിയും സ്വായത്തമാക്കിയിരുന്നു. എന്നാൽ മദ്രാസിലെത്തിയതോടെ സംഘത്തലവനായ ഗ്രോവ്സ് തൻ്റെ തീരുമാനം മാറ്റുകയും മദ്രാസിൽ തുടരാനായി ഗുണ്ടർട്ട് ഉൾപ്പടെ തന്നോടൊപ്പം എത്തിയ പുതിയ മിഷണറി സംഘത്തെ അതിനായി നിർബന്ധിക്കുകയും ചെയ്തു. മനസില്ലാമനസോടെയാണെങ്കിലും ഗുണ്ടർട്ടിന് ഈ തീരുമാനത്തോട് വഴങ്ങേണ്ടതായി വന്നു. അപ്പോൾമുതൽ ഗുണ്ടർട്ട് തമിഴും അഭ്യസിപ്പാൻ തുടങ്ങി. ഗ്രോവ്സിൻ്റെ പുത്രന്മാരെ ദൈവശാസ്ത്രവും, തത്വശാസ്ത്രവും പഠിപ്പിക്കുക എന്നൊരുദ്ദേശം കൂടിയുണ്ടായിരുന്ന ഗുണ്ടർട്ടിനെ, പഠനത്തോടുള്ള അവരുടെ വിമുഖത തെല്ലൊന്നുമല്ല വ്യാകുലപ്പെടുത്തിയത്. 

ഇപ്രകാരം ഏകദേശം നിരാശയിലായിരിക്കുമ്പോൾ ഒരുദിവസം ഗ്രോവ്സ് ഗുണ്ടർട്ടിനെ വിളിച്ച് ഒരു ദൗത്യം ഏല്പിച്ചു. അക്കാലത്ത് തിരുനെൽവേലിയിൽ മിഷൻപ്രവർത്തനം നടത്തിക്കൊണ്ടിരുന്ന റെനിയസ് (Charles Theophilus Ewald Rhenius, “Apostle of Tirunelveli”) എന്ന ജർമൻ മിഷണറിയെക്കുറിച്ച് ചില അപവാദപ്രചാരണങ്ങൾ ഗ്രോവ്സിൻ്റെ ചെവിയിലെത്തുകയുണ്ടായി. ആ ദേശത്തെ വേലയ്ക്കായി ഏകദേശം 13,000 രൂപ ഗ്രോവ്സ് റെനിയസിനു സംഭാവന ചെയ്തിരുന്നു. താൻ കേട്ട വിവരങ്ങളുടെ നിജസ്ഥിതി കണ്ടെത്തുകയെന്ന ഒരു രഹസ്യദൗത്യവുമായി ഗുണ്ടർട്ടിനെ അവിടേയ്ക്ക് അയയ്ക്കുവനായാണ് ഗ്രോവ്സ് ഗുണ്ടർട്ടിനെ വിളിപ്പിച്ചത്. 

തിരുനെൽവേലിയിലെത്തി റെനിയസിനെ കണ്ട ഗുണ്ടർട്ടിന് തങ്ങൾകേട്ട അപവാദങ്ങളിൽ യാതൊരു വാസ്തവവുമില്ല എന്ന് മനസിലായി. തന്നെയുമല്ല, തിരുനെൽവേലിയിലെ മിഷൻപ്രവർത്തനം അതിശക്തമായി നടക്കുന്നതിനു സാക്ഷിയാകാനും അദ്ദേഹത്തിനായി. ആത്മസമർപ്പണത്തോടെയും അത്യുത്സാഹത്തോടെയും ദിനംപ്രതി കർത്താവിൻ്റെ വേല ചെയ്യുന്ന റെനിയസിൻ്റെ പ്രവർത്തനങ്ങൾ കണ്ട് ഗുണ്ടർട്ടിൻ്റെ മനംനിറഞ്ഞു. 1837 മാർച്ച് മാസം വരെ റെനിയസിനോടൊപ്പം താമസിച്ചതിനുശേഷമാണ് തിരികെ ഗ്രോവ്സിൻ്റെ അടുക്കലേയ്ക്ക് അദ്ദേഹം മടങ്ങിയത്. ക്രിസ്തുവിൻ്റെ ഒരു നല്ല ഭടനായി ആത്മിക അടർക്കളത്തിൽ പോരാടാനാണ് തൻ്റെ നിയോഗമെന്ന് ഗുണ്ടർട്ട് അവിടെവെച്ച് തിരിച്ചറിഞ്ഞു, ആ ദൗത്യത്തിനായി തന്നെത്തന്നെ പൂർണ്ണമായി സമർപ്പിക്കുകയും ചെയ്തു.ഗുണ്ടർട്ടിനെ യാത്രയാക്കുമ്പോൾ റെനിയസ് അദ്ദേഹത്തോട്: “എന്നെങ്കിലുമൊരിക്കൽ നിങ്ങൾക്ക് സ്വതന്ത്രമായി പ്രവർത്തിക്കാൻ അനുവാദം ലഭിക്കുന്നുവെങ്കിൽ തിരുനെൽവേലിയിലെ പ്രവർത്തനത്തിനു പ്രാഥമിക പരിഗണന കൊടുക്കണം” എന്ന് അഭ്യർത്ഥിച്ചു.
ഇങ്ങനെ നിറഞ്ഞ ആവേശത്തോടെ തിരികെ മദ്രാസിൽ എത്തിയപ്പോഴാകട്ടെ, ഗ്രോവ്സ് കുടുംബത്തിൻ്റെ തകർച്ചയുടെ ദുഃഖവാർത്തയാണ് ഗുണ്ടർട്ട് കേട്ടത്. അതോടെ ആ സംഘത്തിലുണ്ടായിരുന്നരെല്ലാം “ഇനിയെന്തു ചെയ്യേണ്ടൂ” എന്ന ധർമ്മസങ്കടത്തിലുമായി. ക്രമേണ ഗുണ്ടർട്ടും ഗ്രോവ്സുമായുണ്ടായിരുന്ന സ്‌നേഹവും തണുത്തു തുടങ്ങി. ഗുണ്ടർട്ടിനെപ്പോലെ അച്ചടക്കവും കൃത്യനിഷ്ഠയും ഉണ്ടായിരുന്ന ഒരു വ്യക്തിക്ക്, ഗ്രോവ്സിൻ്റെ മിഷനിലെ അനിശ്ചിതത്വം താങ്ങാവുന്നതിലധികമായിരുന്നു. 

ഒടുക്കം ചിറ്റൂർ എന്ന സ്ഥലത്ത് പോയി കർത്താവിൻ്റെ വേലചെയ്‌വാൻ ഒരു അവസരം ഗുണ്ടർട്ടിനു കൈവരികയും അവിടേയ്ക്ക് പോയി പ്രവർത്തിക്കുകയും ചെയ്തു. ആ ദേശത്ത് അദ്ദേഹം വളരെ അദ്ധ്വാനിച്ചുവെങ്കിലും തൻ്റെ പ്രതീക്ഷകൾക്കൊപ്പമുള്ള ഒരു ഫലം അവിടെക്കാണാനായില്ല. അതുകൂടാതെ, ഇന്ത്യയിലെത്തിയതിനു ശേഷം ഏകദേശം 2 വർഷത്തോളമായിട്ടും തൻ്റെ സ്വദേശത്തുനിന്നും ഒരു കത്ത് പോലും ഗുണ്ടർട്ടിന് ലഭിച്ചില്ല (അവയൊക്കെ വഴിയിൽ നഷ്ടപ്പെട്ടതായാണ് കരുതപ്പെടുന്നത്). ഇങ്ങനെ താൻ വളരെ ഏകാന്തത അനുഭവിച്ച നാളുകളായിരുന്നു അത്. അങ്ങനെയായിരുന്നെങ്കിൽക്കൂടി ഗുണ്ടർട്ട് ഇതിനോടകം ഭാരതത്തെ തൻ്റെ രണ്ടാം സ്വദേശമായി കരുതാൻ തുടങ്ങി. ഗുണ്ടർട്ടിൻ്റെ ഏകാന്തതകണ്ട ചില ഇംഗ്ലീഷ് സഹപ്രവർത്തകർ അദ്ദേഹത്തോട് ഗ്രോവ്സിൻ്റെ സംഘാംഗമായ ജൂലിയ ഡിബോവ എന്ന യുവതിയെ വിവാഹം കഴിക്കുന്ന കാര്യം പരിഗണിക്കാൻ ആവശ്യപ്പെട്ടു. എന്നാൽ ശുശ്രൂഷയുടെ കാര്യത്തിൽ ഒരു സ്ഥിരത ലഭിക്കാത്തതിനാൽ ഗുണ്ടർട്ടിന് അക്കാര്യത്തിൽ ധൈര്യം വന്നില്ല. ഗ്രോവ്സുമായുണ്ടായിരുന്ന കരാർ കേവലം നാലഞ്ച് വർഷത്തേയ്ക്ക് മാത്രമായിരുന്നതിനാൽ അതിനുശേഷം എന്ത് എന്നത് ഒരു ഗുണ്ടർട്ടിനു മുമ്പിൽ ഒരു വലിയ ചോദ്യചിഹ്നമായിരുന്നു.

അങ്ങനെയിരിക്കെ 1838 ജൂൺ 5൹ റെനിയസ് അന്തരിച്ചു എന്ന വാർത്ത ചിറ്റൂരിലുമെത്തി. ഇതറിഞ്ഞ ഗ്രോവ്സ് ഗുണ്ടർട്ടിനോട് “ഇതൊരു വിളിയെന്ന് തോന്നുന്നുവെങ്കിൽ തിരുനൽവേലിയെ വേലസ്ഥലത്തേയ്ക്ക് ചെന്ന് അവിടുള്ള സഹോദരന്മാരെ സഹായിച്ചാൽ നന്നായിരിക്കും” എന്ന് പറഞ്ഞു. മുമ്പൊരിക്കൽ റെനിയസ് തന്നെ തിരുനെൽവേലിയിലേയ്ക്ക് ക്ഷണിച്ചത് ഹൃദയത്തിൽ കരുതിയിരുന്നതിനാൽ അവിടേയ്ക്ക് പോകുവാൻ ഗുണ്ടർട്ട് തയാറായി. അവിടെത്തുമ്പോൾ റെനിയസിനെ കാണാനാവില്ലല്ലോ എന്ന് മാത്രമായിരുന്നു തൻ്റെ ദുഃഖം. അതുകൊണ്ട് തിരുനെൽവേലിയിലെ സഹോദരന്മാരോട് “ഞാൻ സഹായത്തിനായി മാത്രമല്ല, സ്ഥിരമായി നിങ്ങളോടൊന്നിച്ച് പ്രവർത്തിക്കാൻ അങ്ങുവരും” എന്ന് അറിയിച്ചു. തിരുനെൽവേലിയിലേയ്ക്ക് പുറപ്പെടും മുമ്പേ വിവാഹിതനാകുന്നത് നന്നായിരിക്കുമെന്ന് അവിടെയുള്ളവർ ഗുണ്ടർട്ടിനെ അറിയിച്ചതനുസരിച്ച് ഗ്രോവ്സ് വഴി തന്നെ വിവാഹം കഴിക്കാൻ താത്പര്യമുണ്ടോ എന്ന് ജൂലിയയോട് അദ്ദേഹം അന്വേഷിച്ചു. കർത്താവിൻ്റെ വേലയിൽ അതീവതത്പരയായിരുന്ന ആ യുവതിയാകട്ടെ “താങ്കൾ ജീവപര്യന്തം മിഷൻവേല ചെയ്യാൻ നേർന്നിരിക്കുന്നുവെങ്കിൽ ഞാൻ വിശ്വാസത്തോടും നന്ദിഭാവത്തോടും കൂടെ സമ്മതിക്കും” എന്ന് മറുപടിയും നൽകി. 1838 ജൂലൈ മാസം 23൹ അവരുടെ വിവാഹം നടന്നു, 2 ദിവസങ്ങൾക്ക് ശേഷം ആ യുവമിഷണറിമാർ തിരുനെൽവേലിയെ ലക്ഷ്യമാക്കി യാത്രയും തിരിച്ചു. വർഷങ്ങൾ നീണ്ട അനിശ്ചിതത്വത്തിന് ഒടുവിൽ ഒരു മാറ്റം വന്നതിനാൽ ഇരുവരും വളരെ സന്തോഷിച്ചു. [മദ്രാസിലെ തങ്ങളുടെ സുഹൃത്ബന്ധങ്ങൾ ഉപേക്ഷിക്കുന്നത് മാത്രമായിരുന്നു അവർക്ക് കഠിനമായി തോന്നിയത്. പ്രത്യേകിച്ച് ജൂലിയയുടെ സ്കൂളിലെ കുട്ടികൾ അവരെ വിട്ട് പോകരുതേയെന്ന് അപേക്ഷിച്ചു വളരെ കരഞ്ഞപ്പോൾ. ഗ്രോവ്സ് ആകട്ടെ എൻ്റെ വലങ്കൈയ്യും ഇടങ്കൈയ്യും (ഗുണ്ടർട്ടും ജൂലിയയും) പോയിക്കഴിഞ്ഞാൽ എൻ്റെ അവസ്ഥ എന്താകും എന്ന് ദുഃഖിതനായി പ്രലപിച്ചു.] 

ഗുണ്ടർട്ടിനും ജൂലിയയ്ക്കും പ്രിയപ്പെട്ടവരെ പിരിയുന്നതിൽ ദുഃഖമുണ്ടായിരുന്നുവെങ്കിലും തങ്ങളുടെ ശിഷ്ടജീവിതം ക്രിസ്തുവിൻ്റെ വേലചെയ്യുവാനുള്ള വയലായ തിരുനെൽവേലിയിലേയ്ക്ക് അത്യധികം ആകാംക്ഷയോടെയും അതിലേറെ ആവേശത്തോടെയും ആണ് അവർ പുറപ്പെട്ടത്. ആ യാത്രയിലുടനീളം അവർ അങ്ങാടികളിൽ പ്രസംഗിക്കയും അനേകരോട് സുവിശേഷം പങ്കുവെയ്ക്കുകയും ചെയ്തു. ആ സന്തോഷം പക്ഷെ അധികം നീണ്ട് നിന്നില്ല. യാത്ര തൃശ്ശിനാപ്പള്ളിയിൽ എത്തിയപ്പോൾ തിരുനെൽവേലിയിൽനിന്നും വന്ന ഒരു കത്തിലെ വിവരങ്ങൾ അവരുടെ പ്രതീക്ഷകൾക്കും ആവേശത്തിനും മങ്ങലേൽപ്പിക്കുന്നുവ ആയിരുന്നു. 

തിരുനെൽവേലിയിൽ കർത്താവിൻ്റെ വേലയ്ക്കായി ജീവിതം ചെലവിടാൻ ഇറങ്ങിത്തിരിച്ച ആ യുവകുടുംബത്തെ മലബാറിലെത്തിച്ച കത്തിൻ്റെ കഥ അടുത്തലക്കതിൽ.
