ആമുഖം
-------

വളരെ ചെറുപ്പം മുതൽ കേൾക്കുന്ന ഒരു പേരാണ് ഡോ. ഹെർമൻ ഗുണ്ടർട്ടിൻ്റേത്. എന്നിരുന്നാലും അദ്ദേഹത്തെക്കുറിച്ച് വളരെ പരിമിതമായ അറിവു മാത്രമേ എനിക്കുണ്ടായിരുന്നുള്ളൂൂ. അങ്ങനെയിരിക്കേയാണ് കേരളത്തിൻ്റെ പുരാതനരേഖകളുടെ അന്വേഷണത്തിലൊരിക്കൽ ഡോ. ഹെർമൻ ഗുണ്ടർട്ടിൻ്റെ ജീവിതചരിത്രം വിവരിക്കുന്ന ഒരു ഗ്രന്ഥം കാണുവാനിടയായത്. ഒറ്റയിരിപ്പിന് അത് വായിച്ച് തീർന്നുകഴിഞ്ഞപ്പോൾ മുതൽ ആ അത്ഭുതവ്യക്തിത്വത്തെക്കുറിച്ച് ലോകത്തെ അറിയിക്കേണം എന്ന് ആഗ്രഹമുണ്ടായി. അതിനായി ആദ്യം ചെയ്തകാര്യം പ്രസ്തുത പുസ്തകം digitize ചെയ്ത് ഓൺലൈനായി പ്രസിദ്ധീകരിക്കുക എന്നതായിരുന്നു. 

തുടർന്ന് ആ പുസ്തകം വിക്കി ഗ്രന്ഥശാലയിലുൾപ്പെടുത്തി OCR ചെയ്ത് text ആക്കിയെടുത്ത് തെറ്റുതിരുത്തൽ ചെയ്യാൻ ആരംഭിച്ചു. എന്നാൽ അധികം വൈകുന്നതിനുമുമ്പേ, വിക്കി ഗ്രന്ഥശാലാ പ്രവർത്തകർ ചില നിർദ്ദേശങ്ങൾ തരുകയും അത് ഈ പ്രൊജക്റ്റിന് അനുയോജ്യമല്ല എന്ന് തോന്നിയതിനാൽ ഞാനത് നിർത്തിവെയ്ക്കുകയും ചെയ്തു. അപ്പോഴും ഈ ചരിത്രം പൂർണമായി വെളിയിൽ കൊണ്ടുവരുവാൻ സാധിക്കതെ വന്നതിൽ അല്പം വിഷമം മനസിലവശേഷിക്കുകയുമുണ്ടായി.

അങ്ങനെയിരിക്കെ `2017-18` കാലഘട്ടങ്ങളിൽ ജർമനിയിലെ ത്യൂബിംഗൻ യൂണിവേർസിറ്റിയുടെ ഗുണ്ടർട്ട് ലെഗസി പ്രൊജക്റ്റ് ആരംഭിച്ചത്. ഗുണ്ടർട്ട് ഈ യൂണിവേർസിറ്റിയിലെ ഒരു വിദ്യാർഥിയായിരുന്നു. ഇന്ത്യയിൽനിന്നും മടങ്ങിയപ്പോൾ തൻ്റെ കൈവശമുണ്ടായിരുന്ന രേഖകളും പുസ്തകങ്ങളുമൊക്കെ ഗുണ്ടർട്ട് ജർമനിയിലേയ്ക്ക് കൊണ്ടുപോയിരുന്നു. ഈ ശേഖരത്തിൽ പെട്ട കുറെയധികം ഗ്രന്ഥങ്ങൾ അന്നദ്ദേഹം ത്യൂബിംഗൻ യൂണിവേർസിറ്റിയുടെ പുസ്തകശേഖരത്തിലേയ്ക്ക് കൊടുക്കുകയും ചെയ്തു. ഈ ശേഖരങ്ങൾ ഈ അടുത്തകാലത്ത് സ്കറിയ സഖറിയസാർ തൻ്റെ ത്യൂബിംഗൻ സന്ദർശനത്തിനിടെ കണ്ടെത്തുകയും 50,000-ൽ അധികം പേജുകൾ വരുന്ന ആ ശേഖരത്തെ പൊതുഇടത്തിലെത്തിക്കാനുള്ള ശ്രമങ്ങൾ ആരംഭിക്കുകയും  ചെയ്തു. ഇക്കാര്യങ്ങളെക്കുറിച്ചുള്ള കൂടുതൽ വിവരങ്ങൾ താഴെക്കൊടുത്തിരിക്കുന്ന ഓൺലൈൻ ലേഖനങ്ങളിൽ ലഭ്യമാണ്.

https://shijualex.in/gundert_legacy_project_malayalam_unicode/ [ഗുണ്ടർട്ട് ലെഗസി പദ്ധതി]
https://shijualex.in/my-experience-with-the-gundert-legacy-project/[അനുഭവക്കുറിപ്പുകൾ]
https://www.gundert-portal.de/?page=home[ഈ പദ്ധതിയിലൂടെ പുറത്തുവന്ന പുസ്തകങ്ങളും രേഖകളും]

ഈ പദ്ധതിയിൽ സാങ്കേതിക സഹായവും, കുറച്ചെങ്കിലും നേരിട്ടുള്ള സഹായവും ചെയ്യാൻ എനിക്കും സാധിച്ചു. ഇക്കാലയളവിൽ ഗുണ്ടർട്ടിനെക്കുറിച്ചും അദ്ദേഹത്തിൻ്റെ സംഭാവനകളെക്കുറിച്ചും കൂടുതലായി മനസിലാക്കുവാനും ആ മഹത്‌വ്യക്തിത്വത്തോടുള്ള സ്നേഹബഹുമാനങ്ങൾ വർദ്ധിച്ചുവരുവാനുമിടയായി.

